use_frameworks!

platform :ios, '9.0'

target 'LKCommonUIModule_Example' do
  pod 'LKCommonUIModule', :path => '../'
#  pod 'LKMacroCategoryModule', :path => '../../LKMacroCategoryModule'
  pod 'LKMacroCategoryModule', :git => 'https://github.com/kaige1123/LKMacroCategoryModule.git'

  target 'LKCommonUIModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
