use_frameworks!

platform :ios, '9.0'

target 'LKCommonUIModule_Example' do
  pod 'LKCommonUIModule', :path => '../'

  target 'LKCommonUIModule_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
